#
# A configuration file example
# New to TOML? Learn it in 5 minutes https://toml.io/en/
#

# The path where weekly updates should be created (in the hosting repository)
# Note this string is a Liquid template and `{{ date }}` will be replaced by
# the date of the week.
weekly_update_path = "discussions/{{ date | dates.sortable }} weekly.md"

# List of (extra) users that should be included as PR reviewers
additional_writers = ["handle1", "handle2"]

# Teams to include in the weekly update (this is a TOML array of tables so you can
# repeat this whole block for each teams you have)
[[teams]]
name = "Team name"
writers = ["handle3"]
