name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore ./src/WeeklyDrafter.sln

      - name: Build
        run: dotnet build ./src/WeeklyDrafter.sln --no-restore

      - name: Test
        run: dotnet test ./src/WeeklyDrafter.Tests/WeeklyDrafter.Tests.csproj --no-build

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results/**/*.xml
            test-results/**/*.trx
            test-results/**/*.json
