name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    # For EnricoMi/publish-unit-test-result-action
    permissions:
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore ./src/WeeklyDrafter.sln

      - name: Build
        run: dotnet build ./src/WeeklyDrafter.sln --no-restore

      - name: Test
        run: dotnet test ./src/WeeklyDrafter.Tests/WeeklyDrafter.Tests.csproj --no-build --logger:trx

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            **/TestResults/*.trx
